### ISSUE TITLE
gtk3 port

### ISSUE THREAD

**Issue by mazes-80** [wdlkmpx/gmrun#3]
Hi, thanks for the effort on porting to gtk3.
I maintain a port of gmrun to gtk also: https://gitlab.com/mazes_80/gmrun

I don't know if you seen the buffer overflow error in the history file writer.

If you like you can find my contact from the fork I maintain. Sad you didn't notice it was already done.

**Comment by wdlkmpx** [comment]
Hello mazes-80, yes I was aware of you fork, in fact I used many parts of your code and you're credited in the author's file and you're also the author of some commits. I was stuck in the GtkCList -> GtkTreeView stuff when I found your fork and adapted the code to my repo, and as I edited other projects I came to understand how it works and improved the code I borrowed.

As I was porting your code I decided to do things a bit differently 'cause my stuff was already different. I used it as the starting point but ended simplifying things and complicating other parts (XDG + custom extension and url handlers).

I also removed all the references to GString, I didn't use GKeyFile, I fixed several memory leaks I identified and so on, so this 1.0 verson retains basically all the features so that the BSD guys also like it (I've read they hate freedesktop and systemd). But I'm not sure if it was the correct thing.

**Comment by wdlkmpx** [comment]
I wonder how did you became aware of this repo, today a new version was released, but something must have happened for you to notice it... where? 'cause you're not following the project. And I may have @ mentioned you once in a commit perhaps, but that was a year ago maybe.

Don't feel bad, your code has been used and heavily modified... but it's there. This repo has 0 gtk3 deprecation warnings with gtk 3.22, I'm yet to test it with gtk 3.24, but all the gtk3 issues have been resolved so far, you might want to take a look to fix gtk3-specific issues in your repo.

**Comment by wdlkmpx** [comment]
There's one thing I've been meaning to do: rename the repo to GtkRun.

The name is gmrun, but the long name is Gnome Completion Run, and can't be allowed.
https://sourceforge.net/projects/gmrun/
https://wiki.archlinux.org/index.php/Gmrun

But I see GtkRun is a python app amd maybe the name of some other apps, maybe gwrun makes more sense.

**Comment by mazes-80** [comment]
GtkTreeView:
 yes migration from gtkclist was "the" tricky part.
ports are prone to errors if the TreeModel is bad: in compiz-boxmenu I can't fix the model and I got warnings flood, too much details seems to be hidden by python gtk3, with pygtk it was ok. (make me think I should ping compiz-reloaded team to push the latest parts of my PR, as they only included wip ones)

Personally I don't use systemd but openrc (devuan, gentoo), but even if it's "big mess" I rather like xdg. 
I didn't had any issue running without systemd at all (no elogind on the box I use for this message)
So I assume GKeyFile isn't retained to skip xdg ?

Yes, there's a bunch of warning about new gtk3 deprecation, I didn't touch the code for a while.

I don't use github much, but still created an account. At the time I did the port, I wanted to share my work and opened a ticket on the gentoo bugtracker, I got some helpful feedback from users there, one recently noticed your version.
I think now I'm the proxy-maintainer of the gentoo package, so I have to look at the things you added and made different, and may use your version  at one point, but I'm slow to do things (less compile warnings is always nice).

Thanks for credits, an email to notice me about your work may had been better sharing experience. I wrote a lot of mail to many open project devs, sometimes with really stupid questions, and generally people appreciate this communication.

About name, copyrights or so I don't know, just change the acronym to "geeks must run", and gmrun is not more "gnome
completion run". It would also be good as some geeks don't do enough sport.

**Comment by wdlkmpx** [comment]
I didn't use GKeyFile because I retained the option to use custom extension and file handlers, I implemented my own config_file.c trying to keep the same behavior, it cannot dereference more than one variable though.

I do use freedesktop stuff... I used to produce my own distro with properly crafted xdg stuff. 

I think I'll also add gtk4 support while retaining gtk3 and gtk2 compatibility... I added GtkApplication code for gtk3 months ago but gmrun crashed, but after simplifying the gtkcompletionline stuff... I added it again recently and it works. That gives me hope.

I usually don't use email to communicate, send patches, etc. I just do things in github, and do sometimes reply through email to issues, and I guess I'll try to be more active  on gitlab. But it depends on several factors.

**Comment by mazes-80** [comment]
I finally took a look at your code, really quick but:
- gtkcompat.h: really better than the way I did it
- custom handlers are still present and you expose USE_GLIB_XDG configuration option which may be faster as the default custom handler seems to be xdg-open. still retaining compat is good for old users.
- GKeyFile: I really like the config file written when it is launched for the first time (new install, user ...), i didn't looked if you copy default config from outside config_prefs.c

Would you be interested in a PR about a build time switch allowing xdg spec for config and history file
- XDG_CACHE_HOME/gmrun_history
- XDG_CONFIG_HOME/gmrun

this switch not turned on at ./configure time let those files at their old place.

**Comment by wdlkmpx** [comment]
gmrunrc is currently not copied to the home directory, it would be better if gmrun itself generated the config file, but currently there's no code to that.
It would be easier with GKeyFile of course but that breaks old stuff and documentation, tutorials, wikis must change as well, gmrunrc -> gmrun.ini  ... That change alone = gmrun 2.0w
